name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for React app
        working-directory: ./react-app
        run: docker build -t react-app .

      - name: Generate deployment package
        run: |
          echo "Contents of root directory:"
          ls -l
          echo "Contents of react directory:"
          ls -l react-app
          echo "Contents of react/dist directory:"
          ls -l react-app/dist
          mkdir -p deploy
          cp -r ./react-app/dist/* deploy/
          cp ./react-app/package.json deploy/
          cp ./react-app/Procfile deploy/
          echo "Contents of deploy directory:"
          ls -l deploy

          zip -r deploy.zip deploy .ebextensions .platform -x "*.git*" "*__pycache__*" "*.pytest_cache*" "*.venv*" "node_modules/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: cicd
          environment_name: Cicd-env-1
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
          wait_for_deployment: true